# Generated by Django 3.2.3 on 2021-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210618_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ManyToManyField(related_name='companies', to='main.Industry'),
        ),
    ]
