# Generated by Django 3.2.3 on 2021-06-22 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210618_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='remote',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('p', 'Partial'), ('n', 'No'), ('u', 'Unknown')], default='u', max_length=1),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='main.country')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobposts', to='main.city'),
        ),
    ]
